// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_class_diagram;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/************************************************************/
/**
 * 
 */
public class Administrator {
	/**
	 * 
	 */
	protected String nume;
	/**
	 * 
	 */
	protected String id;
	/**
	 * 
	 */
	protected String email;

	public Administrator(String nume, String id, String email) {
		super();
		this.nume = nume;
		this.id = id;
		this.email = email;
	}

	/**
	 * 
	 * @param id_bilet 
	 */
	public void anuleazaBilet(String id_bilet) {
	}

	/**
	 * 
	 */
	public void resetareParola() {
		
	}

	/**
	 * 
	 */
	public void editareDetaliiUtilizator() {
		
	}

	/**
	 * 
	 */
	public void adaugareZbor() {
	}

	/**
	 * 
	 */
	public void intarziereZbor(Zbor zbor, int minute) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy MMM dd HH:mm");
		zbor.timestampDecolare.add(Calendar.MINUTE, minute);
		zbor.timestampAterizareDestinatie.add(Calendar.MINUTE, minute);
		System.out.println(sdf.format(zbor.timestampDecolare.getTime()));
		System.out.println(sdf.format(zbor.timestampAterizareDestinatie.getTime()));
	}
	

	/**
	 * 
	 */
	public void anulareZbor() {
	}

	/**
	 * 
	 */
	public void stergereUtilizator() {
	}
}
