// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_class_diagram;

/************************************************************/
/**
 * 
 */
public class Client {
	/**

	 * 
	 */
	protected String nume;
	/**
	 * 
	 */
	protected String prenume;
	/**
	 * 
	 */
	protected String id;
	/**
	 * 
	 */
	protected String cnp;
	/**

	 */
	protected String email;
	/**
	 * 
	 */
	public Bilet[] bilet; // e redundant ca avem vector de bilete si la client si la cos
	/**                   // la fel si cu aduga/sterge bilet
	 * 
	 */
	public Cos cos;
	
	public Client(String id, String nume, String prenume, String cnp, String email, Cos cos) {
		super();
		this.nume = nume;
		this.prenume = prenume;
		this.id = id;
		this.cnp = cnp;
		this.email = email;
		this.cos = cos; // compozitie!!!!!!!
		
	}

//	public void anuleazaBilet(String id_bilet) {
//	}

	/**
	 * 
	 */
	public void afisareInformatiiClient() {
		System.out.println(id +  nume + prenume + cnp + email);
		System.out.println("=== CLIENT " + this.id + " ===");
		System.out.println("Nume: " + this.nume);
		System.out.println("Prenume: " + this.prenume);
		System.out.println("CNP: " + this.cnp);
		System.out.println("Email: " + this.email);
		System.out.println("COS: ");
		System.out.println("Numar bilete: " + this.cos.nrBilete);
		this.cos.afisareBilete();
		System.out.println("=== ================= ===");

	}

	/**
	 * 
	 * @param id_bilet 
	 */
//	public void adaugaBilet(String id_bilet) {
//	}

	/**
	 * 
	 */
	public void afisareBilete() {
		for(int i=0;i<this.bilet.length;i++) {
			bilet[i].afisare();
		}
	}
}
