// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1_class_diagram;

/************************************************************/
/**
 * 
 */

public class OptiuniAditionaleBilet {
	/**
	 * 
	 */
	public int clasa;
	/**
	 * 
	 */
	public int nrBagaje;
	/**
	 * 
	 */
	public int marimiBagaje;
	/**
	 * 
	 */
	public float greutateAditionala;
	/**
	 * 
	 */
	public float pretTotalOptiuni;

	public OptiuniAditionaleBilet() {
		this.pretTotalOptiuni = 0;
	}
	public OptiuniAditionaleBilet(int clasa, int nrBagaje, int marimiBagaje, float greutateAditionala,
			float pretTotalOptiuni) {
		super();
		this.clasa = clasa;
		this.nrBagaje = nrBagaje;
		this.marimiBagaje = marimiBagaje;
		this.greutateAditionala = greutateAditionala;
		this.pretTotalOptiuni = 0;
		this.computeCost();
	}
	public void setClasa(int clasa2) {
		this.clasa = clasa2;
		
	}
	public void setNrBagaje(int nrBagaje2) {
		// TODO Auto-generated method stub
		this.nrBagaje = nrBagaje2;
		
	}
	public void setGreutateAditionala(int greutateAditionala2) {
		// TODO Auto-generated method stub
		
	}
	public void computeCost() {
		// TODO Auto-generated method stub
		if(this.nrBagaje > 0) {
			this.pretTotalOptiuni += this.nrBagaje * 5.0;
		}
		if(this.clasa == 1) {
			this.pretTotalOptiuni += 15.0;
		} else if(this.clasa == 2) {
			this.pretTotalOptiuni += 10.0;
		} 
		if(this.greutateAditionala > 0) {
			this.pretTotalOptiuni += this.greutateAditionala * 2.0;
		}
	}
	
	public float getPretTotalOptiuni() {
		return this.pretTotalOptiuni;
	}

}
